name: Deploy Natours App to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "Skipping tests..."

      - name: Trigger Render Deployment
        id: deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render Deployment..."
          RESPONSE=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d "{\"serviceId\": \"$RENDER_SERVICE_ID\"}" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys)
          echo "Deploy response: $RESPONSE"

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="Success"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="Failed"
          fi
          PAYLOAD=$(jq -n \
            --arg text "Natours Deployment Status: $STATUS\nBranch: main\nDeployed by GitHub Actions" \
            '{text: $text}')
          curl -X POST -H 'Content-type: application/json' \
            --data "$PAYLOAD" $SLACK_WEBHOOK_URL
